#!/bin/bash
#
# god       Startup script for God monitoring tool.
#
# chkconfig: - 85 15
# description: god monitors your system
#              

CONFIG_FILES=/etc/god/*.god
PID=/var/run/god.pid
LOG=/var/log/god.log
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RETVAL=0

case "$1" in
    start)
      god -P $PID -l $LOG --log-level info
      for config in $CONFIG_FILES; do
        god load $config
      done
      RETVAL=$?
  ;;
    stop)
      kill `cat $PID`
      RETVAL=$?
  ;;
    restart)
      kill `cat $PID`
      god -P $PID -l $LOG --log-level info
      for config in $CONFIG_FILES; do
        god load $config
      done
      RETVAL=$?
  ;;
    status)
      RETVAL=$?
  ;;
    *)
      echo "Usage: god {start|stop|restart|status}"
      exit 1
  ;;
esac

exit $RETVAL
