source 'https://rubygems.org'

gem 'capybara'
gem 'cucumber'
gem 'cucumber-rails'
gem 'ci_reporter'
gem 'database_cleaner'
gem 'differ'
gem 'execjs'
gem 'faraday'
gem 'poltergeist'
gem 'rails', '~> 3.2.0'
gem 'rails-csv-fixtures'
gem 'rails-i18n'
gem 'selenium-webdriver'
gem 'simplecov'
gem 'simplecov-rcov'
gem 'term-ansicolor'
