source 'https://rubygems.org'

gem 'capybara'
gem 'capybara-webkit', '0.12.1'
gem 'cucumber', '1.2.3'
gem 'cucumber-rails'
gem 'ci_reporter'
gem 'differ'
gem 'poltergeist'
gem 'rails', '~> 3.2.0'
gem 'rails-i18n'
gem 'simplecov'
gem 'simplecov-rcov'
