module Daddy
  VERSION = [
    VERSION_MAJOR = '0',
    VERSION_MINOR = '6',
    VERSION_REVISION = '0'
  ].join('.')

  NGINX_VERSION = [
    NGINX_VERSION_MAJOR = '1',
    NGINX_VERSION_MINOR = '13',
    NGINX_VERSION_REVISION = '5'
  ].join('.')

  PASSENGER_VERSION = [
    PASSENGER_VERSION_MAJOR = '5',
    PASSENGER_VERSION_MINOR = '1',
    PASSENGER_VERSION_REVISION = '12'
  ].join('.')
end
