module Daddy
  VERSION = [
    VERSION_MAJOR = '0',
    VERSION_MINOR = '7',
    VERSION_REVISION = '2'
  ].join('.')

  CHROME_DRIVER_VERSION = [
    CHROME_DRIVER_VERSION_MAJOR = '2',
    CHROME_DRIVER_VERSION_MINOR = '40'
  ].join('.')

  GECKO_DRIVER_VERSION = [
    GECKO_DRIVER_VERSION_MAJOR = '0',
    GECKO_DRIVER_VERSION_MINOR = '19',
    GECKO_DRIVER_VERSION_REVISION = '1'
  ].join('.')

  PYTHON_VERSION = [
    PYTHON_VERSION_MAJOR = '3',
    PYTHON_VERSION_MINOR = '6',
    PYTHON_VERSION_REVISION = '3'
  ].join('.')
end
